spring.application.name=BankingSystem

# PostgreSQL Database Configuration (Neon PostgreSQL)
spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-solitary-cell-atcu9hsq.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require}}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:neondb_owner}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:npg_jxT49qJcKYVz}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:123456789012rfrr3456789dnejf0123456789012345678ub9012345678jnjfnknnn}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Brevo (Sendinblue) Email Service Configuration
brevo.api.key=${BREVO_API_KEY:YOUR_BREVO_API_KEY}